import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js";
import {OrbitControls} from "https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js";
const scene=new THREE.Scene();scene.background=new THREE.Color(0x000000);scene.fog=new THREE.FogExp2(0x020006,.006);
const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,500);camera.position.set(0,3.5,28);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;document.querySelector('#scene').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.045;controls.enablePan=false;controls.minDistance=12;controls.maxDistance=55;controls.rotateSpeed=.45;controls.zoomSpeed=.55;
scene.add(new THREE.AmbientLight(0x38204f,.35));const purpleLight=new THREE.PointLight(0xb44cff,5,40,2);purpleLight.position.set(0,2,0);scene.add(purpleLight);const warmLight=new THREE.PointLight(0xffaa44,3,30,2);warmLight.position.set(2,0,1);scene.add(warmLight);
const starCount=1800,starPos=new Float32Array(starCount*3);for(let i=0;i<starCount;i++){const r=35+Math.random()*120,a=Math.random()*Math.PI*2;starPos[i*3]=Math.cos(a)*r;starPos[i*3+1]=(Math.random()-.5)*90;starPos[i*3+2]=Math.sin(a)*r}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(starPos,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xffffff,size:.11,sizeAttenuation:true,transparent:true,opacity:.9})));
function tex(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d'),g=x.createRadialGradient(256,256,20,256,256,256);g.addColorStop(0,'rgba(190,70,255,.75)');g.addColorStop(.22,'rgba(100,20,180,.45)');g.addColorStop(.55,'rgba(35,5,70,.18)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,512,512);return new THREE.CanvasTexture(c)}
const nebula=new THREE.Sprite(new THREE.SpriteMaterial({map:tex(),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,opacity:.48}));nebula.scale.set(55,55,1);nebula.position.set(0,3,-18);scene.add(nebula);const nebula2=nebula.clone();nebula2.material=nebula.material.clone();nebula2.material.opacity=.25;nebula2.scale.set(42,42,1);nebula2.position.set(-16,-8,-10);scene.add(nebula2);
const bh=new THREE.Group();scene.add(bh);bh.add(new THREE.Mesh(new THREE.SphereGeometry(4.1,64,64),new THREE.MeshBasicMaterial({color:0x000000})));
const disc=new THREE.Mesh(new THREE.RingGeometry(4.4,10.5,128,8),new THREE.MeshBasicMaterial({color:0xff9d4d,transparent:true,opacity:.32,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));disc.rotation.x=Math.PI/2.55;disc.rotation.z=.18;bh.add(disc);const pd=new THREE.Mesh(new THREE.RingGeometry(4.8,8.5,128,8),new THREE.MeshBasicMaterial({color:0xb04cff,transparent:true,opacity:.42,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));pd.rotation.x=Math.PI/2.55;pd.rotation.z=.18;bh.add(pd);
function flower(){const g=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:0xffd21f,emissive:0x6b3f00,emissiveIntensity:.55,roughness:.6});for(let i=0;i<6;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.48,12,8),m),a=i*Math.PI/3;p.position.set(Math.cos(a)*.55,Math.sin(a)*.55,0);p.scale.set(.72,1.35,.28);p.rotation.z=a;g.add(p)}g.add(new THREE.Mesh(new THREE.SphereGeometry(.3,16,10),new THREE.MeshStandardMaterial({color:0x7a4800,roughness:.8})));return g}
const flowers=[];for(let i=0;i<32;i++){const f=flower(),r=9+Math.random()*18,a=Math.random()*Math.PI*2;f.position.set(Math.cos(a)*r,(Math.random()-.5)*18,Math.sin(a)*r-3);f.scale.setScalar(.35+Math.random()*.75);f.rotation.set(Math.random()*2,Math.random()*2,Math.random()*6);f.userData={speed:.001+Math.random()*.002,phase:Math.random()*10,baseY:f.position.y};scene.add(f);flowers.push(f)}
const dustCount=600,dustPos=new Float32Array(dustCount*3);for(let i=0;i<dustCount;i++){const a=Math.random()*Math.PI*2,r=5+Math.random()*24;dustPos[i*3]=Math.cos(a)*r;dustPos[i*3+1]=(Math.random()-.5)*14;dustPos[i*3+2]=Math.sin(a)*r-4}const dg=new THREE.BufferGeometry();dg.setAttribute('position',new THREE.BufferAttribute(dustPos,3));scene.add(new THREE.Points(dg,new THREE.PointsMaterial({color:0xc06cff,size:.055,transparent:true,opacity:.7,blending:THREE.AdditiveBlending})));
const music=document.querySelector('#music'),start=document.querySelector('#start');async function begin(){try{await music.play()}catch(e){}start.classList.add('hidden');setTimeout(()=>start.remove(),1300)}start.addEventListener('pointerdown',begin,{once:true});
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();disc.rotation.z+=.0018;pd.rotation.z-=.0025;nebula.material.rotation=t*.012;nebula2.material.rotation=-t*.009;flowers.forEach(f=>{f.position.y=f.userData.baseY+Math.sin(t*f.userData.speed*500+f.userData.phase)*.55;f.rotation.y+=.002+f.userData.speed;f.rotation.z+=.0015});purpleLight.intensity=4.4+Math.sin(t*1.5)*.7;warmLight.intensity=2.6+Math.sin(t*1.1+.8)*.5;controls.update();renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight)});
